### ISSUE TITLE
Vstupní parametry v SeoRouterSource souboru

### ISSUE THREAD

**Issue by elcheco** [Myiyk/seo-router#1]
Ahoj,

hledal jsem nějaké podobné řešení a to tvoje se mi líbí, ale narazil jsem na pár věcí, které se rozcházejí s tím tvým příkladem:

SeoRouterSource::toAction musí mít jako vstupní parametr Nette\Http\Url objekt a ne slug.
SeoRouterSource::toUrl vyžaduje Myiyk\SeoRouter\Action a ne Nette\Application\Request.

Mohl by jsi příklad v dokumentaci upravit?

**Comment by MichalKalita** [comment]
Jasně, opravím to, díky za info.
Nějak mě asi minula notifikaci, že mi to trvalo tak dlouho.

**Comment by MichalKalita** [comment]
Opraveno
